version: '3'
services:
  image-name:
    build: .
    ports:
      - "5000:3000"
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env